version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        dependency-type: "all"
        schedules:
          - interval: weekly
            days: [friday]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

