name: Dependabot

on:
  schedule:
    - cron: '0 3 * * 5' # Runs every Friday at 3 AM UTC
  push:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependabot Action
        uses: dependabot/dependabot-core
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: '/'  
