name: Web Application Deployment Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm test --if-present

      - name: Build Project Artifacts
        run: npm run build --if-present

      - name: Deploy to Vercel Production
        run: |
          npm install --global vercel
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
          echo "Deployment Successfull"