name: Scheduled Tasks

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC

jobs:
  run-task:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run scheduled task
        run: |
          node --version
          npm --version
          echo "Performing maintenance tasks..."
          sudo apt-get update
          sudo apt-get upgrade -y
          
          echo "Performing data backup..."
          mkdir -p backups

          echo "Scheduled tasks completed."
